apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/OWNER/civicpulse-backend
    newName: ghcr.io/OWNER/civicpulse-backend
    newTag: sha-placeholder
  - name: ghcr.io/OWNER/civicpulse-frontend
    newName: ghcr.io/OWNER/civicpulse-frontend
    newTag: sha-placeholder
